[".zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/longmikel/dotfiles/main/zsh/.zshrc"
    refreshPeriod = "1h"
[".zsh/zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/longmikel/dotfiles/main/zsh/.zsh/zshrc"
    refreshPeriod = "1h"
[".zsh/aliases.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/longmikel/dotfiles/main/zsh/.zsh/aliases.zsh"
    refreshPeriod = "1h"
[".zsh/fzf.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/longmikel/dotfiles/main/zsh/.zsh/fzf.zsh"
    refreshPeriod = "1h"
[".zsh/functions.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/longmikel/dotfiles/main/zsh/.zsh/functions.zsh"
    refreshPeriod = "1h"
[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/longmikel/dotfiles/main/tmux/.tmux.conf"
    refreshPeriod = "1h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/NvChad/NvChad.git"
    refreshPeriod = "1h"
