[".zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/longmikel/dotfiles/main/zsh/.zshrc"
    refreshPeriod = "1h"
[".zsh/aliases.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/longmikel/dotfiles/main/zsh/.zsh/alias.zsh"
    refreshPeriod = "1h"
