---
- hosts: localhost
  vars:
        brew_tap:
              - hudochenkov/sshpass
              - tavianator/tap
              - railwaycat/emacsmacport

        brew_packages:
              - atool
              - autojump
              - bash
              - bat
              - bfs
              - chezmoi
              - cmake
              - code-minimap
              - colordiff
              - coreutils
              - cowsay
              - dark-mode
              - dockutil
              - duti
              - exiftool
              - fd
              - ffmpeg
              - figlet
              - findutils
              - fzf
              - gawk
              - ghq
              - gifsicle
              - gitui
              - gnu-getopt
              - gnu-indent
              - gnu-sed
              - gnu-tar
              - gnu-which
              - gnupg
              - gnuplot
              - gnutls
              - graphviz
              - helm
              - htop
              - icdiff
              - isync
              - jump
              - lsd
              - mas
              - mpv
              - msmtp
              - mu
              - ncdu
              - neovim
              - nmap
              - npm
              - pandoc
              - peco
              - pngpaste
              - putty
              - pyenv
              - qpdf
              - qrencode
              - rar
              - reattach-to-user-namespace
              - ripgrep
              - ruby
              - rust
              - starship
              - schappim/ocr/ocr
              - spaceship
              - sshpass
              - stow
              - svn
              - syncthing
              - signal
              - telnet
              - terraform
              - the_silver_searcher
              - tmux
              - trash
              - tree-sitter
              - ugit
              - universal-ctags
              - vim
              - wget
              - wordnet
              - yarn

        brew_packages_remove:

        brew_casks:
              - arc
              - anydesk
              - alt-tab
              - dropbox
              - docker
              - google-chrome
              - google-drive
              - evkey
              - firefox
              - font-cascadia-code
              - font-cascadia-code-pl
              - font-cascadia-mono
              - font-cascadia-mono-pl
              - font-iosevka-curly-slab
              - font-jetbrains-mono-nerd-font
              - font-juliamono
              - font-lato
              - font-source-code-pro
              - postman
              - iterm2
              - karabiner-elements
              - keepassxc
              - lens
              - microsoft-edge
              - microsoft-office
              - microsoft-teams
              - mos
              - rectangle
              - shottr
              - syncthing
              - teamviewer
              - textmate
              - visual-studio-code
              - zalo

        brew_casks_remove:
              - browserosaurus
              - hiddenbar
              - istat-menus
              - keycastr
              - maccy
              - maciasl

        appstore_app:
              - 1440147259 # AdGuard for Safari
              - 937984704 # Amphetamine
              - 1355679052 # Dropover
              - 975890633 # HotKey
              - 1295203466 # Microsoft Remote Desktop
              - 1284863847 # Unsplash Wallpapers
              - 1137397744 # Bitwarden
              - 747648890 # Telegram
              - 1451685025 # WireGuard

  tasks:
        - name: Appstore install apps
          shell: |
                mas install {{ item }}
          with_items: "{{ appstore_app }}"
          tags:
                - appstore

        - name: Brew tap
          shell: |
                HOMEBREW_NO_AUTO_UPDATE=1 brew tap {{ item }}
          with_items: "{{ brew_tap }}"
          tags:
                - brew
                - brew-tap

        - name: Brew install packages
          shell: |
                HOMEBREW_NO_AUTO_UPDATE=1 brew install {{ item }}
          with_items: "{{ brew_packages }}"
          tags:
                - brew
                - brew-packages

        - name: Brew install casks
          shell: |
                HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask {{ item }}
          with_items: "{{ brew_casks }}"
          tags:
                - brew
                - brew-casks
